"""
Exports the trained GradientBoostingRegressor from ml_forecast.py into a
portable JSON format (raw tree arrays + init value + learning rate) so it
can be re-implemented as a pure-JS inference engine and shipped inside the
static frontend -- a genuinely pretrained model doing real inference in the
browser, with zero server dependency at request time.

Only inference (tree traversal) is reimplemented client-side; training
still only ever happens here, offline, in scikit-learn. Run this whenever
ml_forecast.py's training setup changes, then re-copy the output into
polar-ems-web/assets/ml/.

Usage:  python export_ml_model.py
"""
from __future__ import annotations

import json
import sys

import numpy as np

sys.path.insert(0, ".")
from app.ml_forecast import FEATURE_NAMES, generate_training_data
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.model_selection import train_test_split


def export_tree(tree):
    """Flatten a sklearn DecisionTreeRegressor's internal tree_ into plain
    JSON-able arrays. -1 in children_left marks a leaf (children_right will
    also be -1 there); value holds the leaf's predicted contribution for
    every node, but is only read at leaves during traversal."""
    t = tree.tree_
    return {
        "children_left": t.children_left.tolist(),
        "children_right": t.children_right.tolist(),
        "feature": t.feature.tolist(),
        "threshold": t.threshold.tolist(),
        "value": [v[0][0] for v in t.value],
    }


def predict_one_tree(tree_json, x):
    """Pure-Python re-walk of the exported arrays -- used only to verify the
    export is faithful before it's ever ported to JS."""
    node = 0
    while tree_json["children_left"][node] != -1:
        f = tree_json["feature"][node]
        thr = tree_json["threshold"][node]
        node = tree_json["children_left"][node] if x[f] <= thr else tree_json["children_right"][node]
    return tree_json["value"][node]


def predict_from_export(export, x):
    total = export["init"]
    for t in export["trees"]:
        total += export["learning_rate"] * predict_one_tree(t, x)
    return total


def main():
    X, y = generate_training_data(3000)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    model = GradientBoostingRegressor(n_estimators=150, max_depth=3, learning_rate=0.08, random_state=42)
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    metrics = {
        "model_type": "GradientBoostingRegressor (scikit-learn)",
        "test_mae_kw": round(float(mean_absolute_error(y_test, preds)), 2),
        "test_rmse_kw": round(float(mean_squared_error(y_test, preds) ** 0.5), 2),
        "n_train": len(X_train),
        "n_test": len(X_test),
        "n_estimators": model.n_estimators_,
        "max_depth": 3,
        "feature_importances": {name: round(float(v), 4) for name, v in zip(FEATURE_NAMES, model.feature_importances_)},
    }

    export = {
        "model_type": metrics["model_type"],
        "feature_names": FEATURE_NAMES,
        "init": float(model.init_.constant_[0][0]),
        "learning_rate": float(model.learning_rate),
        "trees": [export_tree(model.estimators_[i, 0]) for i in range(model.n_estimators_)],
        "metrics": metrics,
        "trained_at": "generated by export_ml_model.py, same training setup as app/ml_forecast.py",
    }

    # Verify the exported arrays reproduce sklearn's own predictions before
    # anything gets ported to JS -- if this assertion fails, do not ship.
    sklearn_preds = model.predict(X_test)
    export_preds = np.array([predict_from_export(export, x) for x in X_test])
    max_abs_diff = float(np.max(np.abs(sklearn_preds - export_preds)))
    print(f"Verification: max |sklearn - exported| over {len(X_test)} test rows = {max_abs_diff:.10f} kW")
    assert max_abs_diff < 1e-6, "export does not match sklearn's own predictions -- do not ship"

    out_path = "../polar-ems-web/assets/ml/trained_forecaster.json"
    with open(out_path, "w") as f:
        json.dump(export, f)
    import os
    size_kb = os.path.getsize(out_path) / 1024
    print(f"Wrote {out_path} ({size_kb:.1f} KB, {len(export['trees'])} trees)")
    print(json.dumps(metrics, indent=2))


if __name__ == "__main__":
    main()
