"""
POLAR-EMS backend API.

Run locally with:
    uvicorn app.main:app --reload --port 8000

Then open http://127.0.0.1:8000/docs for interactive Swagger docs, or run
../cli.py in a second terminal for a menu-driven text interface.

This backend is a synthetic simulation (see engine.py's module docstring
and README.md) -- there is no connection to real station hardware.
"""

from __future__ import annotations

import asyncio
from contextlib import asynccontextmanager
from typing import Optional

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from .engine import SCENARIOS, SCENARIO_IDS, SimulationEngine

engine = SimulationEngine()
_tick_task: Optional[asyncio.Task] = None
TICK_INTERVAL_SECONDS = 1.0


async def _tick_loop():
    while True:
        try:
            engine.tick()
        except Exception as exc:  # never let a bad tick kill the loop
            print(f"[tick error] {exc!r}")
        await asyncio.sleep(TICK_INTERVAL_SECONDS)


@asynccontextmanager
async def lifespan(app: FastAPI):
    global _tick_task
    _tick_task = asyncio.create_task(_tick_loop())
    print("POLAR-EMS backend started. Simulation clock ticking every "
          f"{TICK_INTERVAL_SECONDS}s of real time.")
    yield
    if _tick_task:
        _tick_task.cancel()


app = FastAPI(
    title="POLAR-EMS API",
    description=(
        "Synthetic microgrid simulation for an isolated polar research station. "
        "Weather, generation, load, battery, diesel and dispatch are computed by an "
        "explicit physical/rules model running on this server -- see /health and README.md."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # dev-friendly default; restrict to your deployed frontend origin(s) in production
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


# --------------------------------------------------------------------------
# request bodies
# --------------------------------------------------------------------------
class SpeedBody(BaseModel):
    speed: int = Field(..., ge=1, le=20, description="Simulated hours per tick multiplier (1, 4, or 12 in the UI)")


class ScenarioBody(BaseModel):
    id: str = Field(..., description="One of: " + ", ".join(sorted(SCENARIO_IDS)))


# --------------------------------------------------------------------------
# health / meta
# --------------------------------------------------------------------------
@app.get("/health", tags=["meta"])
def health():
    return {"status": "ok", "simulated": True, "sim_time": engine.sim_time.isoformat()}


@app.get("/api/station", tags=["meta"])
def station():
    return {
        "name": "Vostok Ridge Station",
        "mode": "SIMULATION",
        "note": "Synthetic telemetry generated by a physical/rules model. Not live station data.",
        "turbine_count": engine.turbine_count,
        "solar_cap_kw": engine.solar_cap_kw,
        "battery_cap_kwh": 500,
        "diesel_rated_kw": 300,
    }


@app.get("/api/scenarios", tags=["meta"])
def scenarios():
    return {"scenarios": SCENARIOS, "active": engine.scenario}


# --------------------------------------------------------------------------
# telemetry
# --------------------------------------------------------------------------
@app.get("/api/telemetry/latest", tags=["telemetry"])
def telemetry_latest():
    return engine.snapshot()


@app.get("/api/telemetry", tags=["telemetry"])
def telemetry_history(limit: int = 100):
    limit = max(1, min(limit, 720))
    return {"count": len(engine.history[-limit:]), "records": engine.history[-limit:]}


@app.get("/api/battery", tags=["telemetry"])
def battery():
    return engine.snapshot()["battery"]


@app.get("/api/generator", tags=["telemetry"])
def generator():
    return engine.snapshot()["diesel"]


# --------------------------------------------------------------------------
# dispatch
# --------------------------------------------------------------------------
@app.get("/api/dispatch/current", tags=["dispatch"])
def dispatch_current():
    return {"mode": engine.mode, "decision": engine.current_decision}


@app.get("/api/dispatch/history", tags=["dispatch"])
def dispatch_history(limit: int = 25):
    limit = max(1, min(limit, 80))
    return {"count": len(engine.decision_log[:limit]), "records": engine.decision_log[:limit]}


# --------------------------------------------------------------------------
# forecast
# --------------------------------------------------------------------------
@app.get("/api/forecast/load", tags=["forecast"])
def forecast_load(horizon: int = 1):
    if horizon not in (1, 6, 12, 24):
        raise HTTPException(400, "horizon must be one of 1, 6, 12, 24")
    errs = engine.forecast_errors[horizon]
    mae = sum(e["abs"] for e in errs) / len(errs) if errs else None
    rmse = (sum(e["sq"] for e in errs) / len(errs)) ** 0.5 if errs else None
    return {
        "horizon_h": horizon, "mae_kw": round(mae, 1) if mae is not None else None,
        "rmse_kw": round(rmse, 1) if rmse is not None else None,
        "samples_scored": len(errs),
        "points": engine.forecast_points[horizon][-48:],
    }


@app.get("/api/forecast/renewables", tags=["forecast"])
def forecast_renewables(horizon: int = 1):
    if horizon not in (1, 6, 12, 24):
        raise HTTPException(400, "horizon must be one of 1, 6, 12, 24")
    return {"horizon_h": horizon, "points": engine.forecast_points[horizon][-48:]}


# --------------------------------------------------------------------------
# alerts / anomalies
# --------------------------------------------------------------------------
@app.get("/api/alerts", tags=["anomalies"])
def alerts(limit: int = 30):
    limit = max(1, min(limit, 60))
    return {"count": len(engine.alerts[:limit]), "alerts": [a.to_dict() for a in engine.alerts[:limit]]}


@app.get("/api/anomalies", tags=["anomalies"])
def anomalies():
    return {
        "health": engine.health,
        "open_alerts": len(engine.alerts),
        "critical_alerts": len([a for a in engine.alerts if a.severity == "critical"]),
    }


# --------------------------------------------------------------------------
# green audit
# --------------------------------------------------------------------------
@app.get("/api/green-audit", tags=["audit"])
def green_audit():
    return engine.green_audit()


# --------------------------------------------------------------------------
# sync / offline
# --------------------------------------------------------------------------
@app.get("/api/sync/status", tags=["sync"])
def sync_status():
    return {
        "online": engine.online, "syncing": engine.syncing, "outbox": engine.outbox,
        "log": engine.sync_log[:20],
    }


@app.post("/api/sync", tags=["sync"])
def sync_now():
    if not engine.online:
        raise HTTPException(409, "cannot sync while offline; call /api/simulation/online first")
    engine.sync_step()
    return sync_status()


# --------------------------------------------------------------------------
# simulation control
# --------------------------------------------------------------------------
@app.post("/api/simulation/start", tags=["simulation"])
def sim_start():
    engine.running = True
    return {"running": engine.running}


@app.post("/api/simulation/pause", tags=["simulation"])
def sim_pause():
    engine.running = False
    return {"running": engine.running}


@app.post("/api/simulation/reset", tags=["simulation"])
def sim_reset():
    engine.reset()
    for _ in range(8):
        engine.tick()
    return {"reset": True, "sim_time": engine.sim_time.isoformat()}


@app.post("/api/simulation/offline", tags=["simulation"])
def sim_offline():
    engine.set_online(False)
    return sync_status()


@app.post("/api/simulation/online", tags=["simulation"])
def sim_online():
    engine.set_online(True)
    return sync_status()


@app.post("/api/simulation/speed", tags=["simulation"])
def sim_speed(body: SpeedBody):
    engine.speed = body.speed
    return {"speed": engine.speed}


@app.post("/api/simulation/scenario", tags=["simulation"])
def sim_scenario(body: ScenarioBody):
    if body.id not in SCENARIO_IDS:
        raise HTTPException(400, f"unknown scenario id '{body.id}'. Valid ids: {sorted(SCENARIO_IDS)}")
    engine.apply_scenario(body.id)
    return {"scenario": engine.scenario or "normal"}
